import { Product } from '@/types'

/**
 * Fallback products used when Sanity is empty or unreachable.
 * Keeps the shop page browsable in development & previews.
 */
export const DEMO_PRODUCTS: Product[] = [
  {
    _id: 'demo-velvet-rouge',
    _type: 'product',
    name_en: 'Velvet Rouge',
    name_ar: 'أحمر شفاه مخملي',
    slug: { current: 'velvet-rouge' },
    price: 18.500,
    images: [],
    collection: 'lip',
    description_en: 'A creamy, long-lasting lipstick with a velvet matte finish.',
    description_ar: 'أحمر شفاه كريمي طويل الأمد بلمسة نهائية مخملية مطفية.',
    inStock: true,
    badge: 'bestseller',
    featured: true,
    shades: [
      { name_en: 'Crimson', name_ar: 'قرمزي', hex: '#8B1A1A' },
      { name_en: 'Berry',   name_ar: 'توتي',   hex: '#6B2C39' },
      { name_en: 'Nude',    name_ar: 'عاري',   hex: '#C9826F' },
      { name_en: 'Mauve',   name_ar: 'موف',    hex: '#9B5A6E' },
    ],
  },
  {
    _id: 'demo-desert-dusk',
    _type: 'product',
    name_en: 'Desert Dusk Palette',
    name_ar: 'باليت غروب الصحراء',
    slug: { current: 'desert-dusk-palette' },
    price: 34.000,
    images: [],
    collection: 'eye',
    description_en: 'Six warm shades inspired by Kuwait sunsets.',
    description_ar: 'ستة ألوان دافئة مستوحاة من غروب الكويت.',
    inStock: true,
    badge: 'new',
    featured: true,
  },
  {
    _id: 'demo-golden-hour',
    _type: 'product',
    name_en: 'Golden Hour Concealer',
    name_ar: 'كونسيلر الساعة الذهبية',
    slug: { current: 'golden-hour-concealer' },
    price: 22.000,
    images: [],
    collection: 'face',
    description_en: 'A radiant concealer that brightens and conceals in one step.',
    description_ar: 'كونسيلر مشع يضيء ويغطي في خطوة واحدة.',
    inStock: true,
    featured: false,
    shades: [
      { name_en: 'Porcelain', name_ar: 'بورسلين',     hex: '#F4DAC4' },
      { name_en: 'Sand',      name_ar: 'رملي',        hex: '#E0B98A' },
      { name_en: 'Caramel',   name_ar: 'كراميل',      hex: '#B68660' },
      { name_en: 'Espresso',  name_ar: 'إسبريسو',    hex: '#5B3922' },
    ],
  },
  {
    _id: 'demo-midnight-kohl',
    _type: 'product',
    name_en: 'Midnight Kohl',
    name_ar: 'كحل منتصف الليل',
    slug: { current: 'midnight-kohl' },
    price: 16.000,
    images: [],
    collection: 'eye',
    description_en: 'Smudge-proof Arabian kohl for the perfect smoky eye.',
    description_ar: 'كحل عربي ضد التلطخ لعينين دخانيتين مثاليتين.',
    inStock: true,
    badge: 'limited',
    featured: false,
  },
  {
    _id: 'demo-rose-ritual',
    _type: 'product',
    name_en: 'Rose Ritual Blush',
    name_ar: 'بلاش وردي',
    slug: { current: 'rose-ritual-blush' },
    price: 26.000,
    images: [],
    collection: 'face',
    description_en: 'A silky powder blush in three petal-soft shades.',
    description_ar: 'بلاش بودرة حريري بثلاث درجات بنعومة البتلات.',
    inStock: true,
    badge: 'new',
    featured: true,
    shades: [
      { name_en: 'Petal', name_ar: 'بتلة', hex: '#E8B8B6' },
      { name_en: 'Dusk',  name_ar: 'غسق',  hex: '#C4827A' },
      { name_en: 'Wine',  name_ar: 'نبيذ', hex: '#923F4D' },
    ],
  },
  {
    _id: 'demo-saffron-glow',
    _type: 'product',
    name_en: 'Saffron Glow Trio',
    name_ar: 'ثلاثية الزعفران المشرقة',
    slug: { current: 'saffron-glow-trio' },
    price: 38.000,
    images: [],
    collection: 'face',
    description_en: 'A highlighter trio crafted from light-reflecting saffron pearl.',
    description_ar: 'ثلاثية هايلايتر مصنوعة من لؤلؤ الزعفران العاكس للضوء.',
    inStock: true,
    featured: true,
  },
  {
    _id: 'demo-smoky-nights',
    _type: 'product',
    name_en: 'Smoky Nights Palette',
    name_ar: 'باليت ليالي الدخان',
    slug: { current: 'smoky-nights-palette' },
    price: 28.000,
    images: [],
    collection: 'eye',
    description_en: 'Eight smoky shades for sultry evening looks.',
    description_ar: 'ثمانية ألوان دخانية لإطلالات مسائية ساحرة.',
    inStock: true,
    badge: 'bestseller',
    featured: true,
  },
  {
    _id: 'demo-lash-luxe',
    _type: 'product',
    name_en: 'Lash Luxe Mascara',
    name_ar: 'ماسكارا فاخرة',
    slug: { current: 'lash-luxe-mascara' },
    price: 19.500,
    images: [],
    collection: 'eye',
    description_en: 'Volumising mascara with conditioning oils.',
    description_ar: 'ماسكارا تكثيف الرموش بزيوت مغذية.',
    inStock: true,
    badge: 'new',
    featured: false,
  },
  {
    _id: 'demo-arabian-kohl',
    _type: 'product',
    name_en: 'Arabian Kohl',
    name_ar: 'كحل عربي أصيل',
    slug: { current: 'arabian-kohl' },
    price: 14.000,
    images: [],
    collection: 'eye',
    description_en: 'Authentic Arabian kohl powder, refined for the modern Kuwaiti woman.',
    description_ar: 'كحل عربي أصيل، مكرر للمرأة الكويتية العصرية.',
    inStock: true,
    featured: false,
  },
  {
    _id: 'demo-brow-sculpt',
    _type: 'product',
    name_en: 'Brow Sculpt',
    name_ar: 'محدد الحواجب',
    slug: { current: 'brow-sculpt' },
    price: 15.500,
    images: [],
    collection: 'eye',
    description_en: 'A dual-ended brow pencil for sculpted, natural-looking brows.',
    description_ar: 'قلم حواجب مزدوج لحواجب طبيعية مرسومة.',
    inStock: true,
    badge: 'limited',
    featured: false,
  },
  {
    _id: 'demo-bridal-set',
    _type: 'product',
    name_en: 'The Bridal Ritual Set',
    name_ar: 'طقم العروس',
    slug: { current: 'bridal-ritual-set' },
    price: 89.000,
    images: [],
    collection: 'gift',
    description_en: 'Our signature lip, eye, and glow trio in a keepsake box.',
    description_ar: 'مجموعة الشفاه والعيون والإشراق في صندوق هدية فاخر.',
    inStock: true,
    badge: 'limited',
    featured: true,
  },
  {
    _id: 'demo-discovery-set',
    _type: 'product',
    name_en: 'Discovery Mini Set',
    name_ar: 'مجموعة الاكتشاف المصغرة',
    slug: { current: 'discovery-mini-set' },
    price: 42.000,
    images: [],
    collection: 'gift',
    description_en: 'Five travel-size minis from the Claraline ritual.',
    description_ar: 'خمسة منتجات بحجم السفر من طقس كالرالاين.',
    inStock: true,
    badge: 'new',
    featured: false,
  },
]
